"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Type, TypeVar

ROOT_DIR = ...
T = TypeVar("T")
class ConfigReader:
    """Read the configuration file."""
    def __init__(self, filepath: str) -> None:
        ...

    @staticmethod
    def for_filename(filename: str) -> Optional[ConfigReader]:
        ...

    def read_toml(self, cls: Type[T], *, fallback: T) -> T:
        ...

    def write_toml(self, data: Any) -> None:
        ...
