"""
This type stub file was generated by pyright.
"""

from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

@mddoc
def accordion(items: dict[str, object], multiple: bool = ..., lazy: bool = ...) -> Html:
    """
    Accordion of one or more items.

    **Example.**

    ```python3
    mo.accordion(
        {"Tip": "Use accordions to let users reveal and hide content."}
    )
    ```

    Accordion content can be lazily loaded:

    ```python3
    mo.accordion({"View total": expensive_item}, lazy=True)
    ```

    where `expensive_item` is the item to render, or a callable that
    returns the item to render.

    **Args.**

    - `items`: a dictionary of item names to item content; strings are
      interpreted as markdown
    - `multiple`: whether to allow multiple items to be open simultaneously
    - `lazy`: a boolean, whether to lazily load the accordion content.
              This is a convenience that wraps each accordion in a `mo.lazy`
              component.

    **Returns.**

    - An `Html` object.
    """
    ...
