"""
This type stub file was generated by pyright.
"""

from typing import Literal
from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

@mddoc
def callout(value: object, kind: Literal["neutral", "warn", "success", "info", "danger"] = ...) -> Html:
    """Build a callout output.

    **Args.**

    - `value`: A value to render in the callout
    - `kind`: The kind of callout (affects styling).

    **Returns.**

    - An HTML object.
    """
    ...
