"""
This type stub file was generated by pyright.
"""

import io
from typing import Any, Optional, Union
from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
Image = Union[str, bytes, io.BytesIO, io.BufferedReader]
Tensor = Any
ImageLike = Union[Image, Tensor]
@mddoc
def image(src: ImageLike, alt: Optional[str] = ..., width: Optional[Union[int, str]] = ..., height: Optional[Union[int, str]] = ..., rounded: bool = ..., style: Optional[dict[str, Any]] = ..., caption: Optional[str] = ...) -> Html:
    """Render an image as HTML.

    **Examples.**

    ```python3
    # Render an image from a local file
    mo.image(src="path/to/image.png")
    ```

    ```python3
    # Render an image from a URL
    mo.image(
        src="https://marimo.io/logo.png",
        alt="Marimo logo",
        width=100,
        height=100,
        rounded=True,
        caption="Marimo logo",
    )
    ```

    **Args.**

    - `src`: a path or URL to an image, a file-like object
        (opened in binary mode), or array-like object.
    - `alt`: the alt text of the image
    - `width`: the width of the image in pixels or a string with units
    - `height`: the height of the image in pixels or a string with units
    - `rounded`: whether to round the corners of the image
    - `style`: a dictionary of CSS styles to apply to the image
    - `caption`: the caption of the image

    **Returns.**

    `Html` object
    """
    ...

