"""
This type stub file was generated by pyright.
"""

from typing import Optional
from marimo._output.hypertext import Html
from marimo._plugins.core.web_component import JSONType

def json_output(json_data: JSONType, name: Optional[str] = ...) -> Html:
    """Build a json output element.

    Args:
    -----
    json_data: JSON-serializable data to display
    name: optional text label

    Returns:
    --------
    A string of HTML for a JSON output element.
    """
    ...
