"""
This type stub file was generated by pyright.
"""

from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
@mddoc
def plain_text(text: str) -> Html:
    """Text that's fixed-width, with spaces and newlines preserved.

    **Args.**

    - `text`: text to output

    **Returns.**

    An `Html` object representing the text.
    """
    ...

