"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

@mddoc
def style(item: object, style: Optional[dict[str, Any]] = ..., **kwargs: Any) -> Html:
    """Wrap an object in a styled container.

    **Example.**

    ```python
    mo.style(item, styles={"max-height": "300px", "overflow": "auto"})
    mo.style(item, max_height="300px", overflow="auto")
    ```

    **Args.**

    - `item`: an object to render as HTML
    - `styles`: a optional dict of CSS styles, keyed by property name
    - `**kwargs`: additional CSS styles
    """
    ...
