"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
@mddoc
def tree(items: list[Any] | tuple[Any] | dict[Any, Any], label: Optional[str] = ...) -> Html:
    """Render a nested structure of lists, tuples, or dicts as a tree.

    **Example.**
    ```python3
    mo.tree(["entry", "another entry", {"key": [0, 1, 2]}], label="A tree.")
    ```
    **Args.**

    - `items`: nested structure of lists, tuples, or dicts
    - `label`: optional text label for the tree

    **Returns.**

    `Html` object
    """
    ...

