"""
This type stub file was generated by pyright.
"""

from typing import Any

def validate_range(min_value: int | float | None, max_value: int | float | None) -> None:
    ...

def validate_between_range(value: int | float | None, min_value: int | float | None, max_value: int | float | None) -> None:
    ...

def validate_number(value: Any) -> None:
    ...

def warn_js_safe_number(*values: int | float | None) -> None:
    ...

def validate_no_integer_columns(df: Any) -> None:
    ...
