"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Generator, List, Optional

@dataclass
class SnippetSection:
    id: str
    html: Optional[str] = ...
    code: Optional[str] = ...


@dataclass
class Snippet:
    title: str
    sections: List[SnippetSection]
    ...


@dataclass
class Snippets:
    snippets: List[Snippet]
    ...


async def read_snippets() -> Snippets:
    ...

def should_ignore_code(code: str) -> bool:
    ...

def get_title_from_code(code: str) -> str:
    ...

def is_markdown(code: str) -> bool:
    ...

def snippet_files() -> Generator[str, Any, None]:
    ...
