"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__version__ = ...
def get_numversion_from_version(v: str) -> tuple[int, int, int]:
    """Kept for compatibility reason.

    See https://github.com/pylint-dev/pylint/issues/4399
    https://github.com/pylint-dev/pylint/issues/4420,
    """
    ...

numversion = ...
