"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
embeddings_migrations = ...
@embeddings_migrations()
def m001_create_tables(db):
    ...

@embeddings_migrations()
def m002_foreign_key(db):
    ...

@embeddings_migrations()
def m003_add_updated(db):
    ...

@embeddings_migrations()
def m004_store_content_hash(db):
    ...

@embeddings_migrations()
def m005_add_content_blob(db):
    ...

