"""
This type stub file was generated by pyright.
"""

embeddings_migrations = ...
@embeddings_migrations()
def m001_create_tables(db): # -> None:
    ...

@embeddings_migrations()
def m002_foreign_key(db): # -> None:
    ...

@embeddings_migrations()
def m003_add_updated(db): # -> None:
    ...

@embeddings_migrations()
def m004_store_content_hash(db): # -> None:
    ...

@embeddings_migrations()
def m005_add_content_blob(db): # -> None:
    ...
