"""
This type stub file was generated by pyright.
"""

from typing import Callable, List

MIGRATIONS: List[Callable] = ...
migration = ...
def migrate(db): # -> None:
    ...

def ensure_migrations_table(db): # -> None:
    ...

@migration
def m001_initial(db): # -> None:
    ...

@migration
def m002_id_primary_key(db): # -> None:
    ...

@migration
def m003_chat_id_foreign_key(db): # -> None:
    ...

@migration
def m004_column_order(db): # -> None:
    ...

@migration
def m004_drop_provider(db): # -> None:
    ...

@migration
def m005_debug(db): # -> None:
    ...

@migration
def m006_new_logs_table(db): # -> None:
    ...

@migration
def m007_finish_logs_table(db): # -> None:
    ...

@migration
def m008_reply_to_id_foreign_key(db): # -> None:
    ...

@migration
def m008_fix_column_order_in_logs(db): # -> None:
    ...

@migration
def m009_delete_logs_table_if_empty(db): # -> None:
    ...

@migration
def m010_create_new_log_tables(db): # -> None:
    ...

@migration
def m011_fts_for_responses(db): # -> None:
    ...

@migration
def m012_attachments_tables(db): # -> None:
    ...

@migration
def m013_usage(db): # -> None:
    ...
