"""
This type stub file was generated by pyright.
"""

import string
from pydantic import BaseModel
from typing import Any, Dict, List, Optional, Tuple

class Template(BaseModel):
    name: str
    prompt: Optional[str] = ...
    system: Optional[str] = ...
    model: Optional[str] = ...
    defaults: Optional[Dict[str, Any]] = ...
    class Config:
        extra = ...


    class MissingVariables(Exception):
        ...


    def evaluate(self, input: str, params: Optional[Dict[str, Any]] = ...) -> Tuple[Optional[str], Optional[str]]:
        ...

    @classmethod
    def interpolate(cls, text: Optional[str], params: Dict[str, Any]) -> Optional[str]:
        ...

    @staticmethod
    def extract_vars(string_template: string.Template) -> List[str]:
        ...
