"""
This type stub file was generated by pyright.
"""

from typing import Callable, List
from marimo._plugins.ui._impl.dataframes.transforms.types import Transform

def python_print_transforms(df_name: str, all_columns: List[str], transforms: List[Transform], print_transform: Callable[[str, List[str], Transform], str]) -> str:
    ...

def python_print_pandas(df_name: str, all_columns: List[str], transform: Transform) -> str:
    ...

def python_print_polars(df_name: str, all_columns: List[str], transform: Transform) -> str:
    ...

def python_print_ibis(df_name: str, all_columns: List[str], transform: Transform) -> str:
    ...
