"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import NoReturn
from pylint.config.arguments_manager import _ArgumentsManager
from pylint.config.arguments_provider import _ArgumentsProvider
from pylint.typing import Options

"""Create UML diagrams for classes and modules in <packages>."""
DIRECTLY_SUPPORTED_FORMATS = ...
DEFAULT_COLOR_PALETTE = ...
OPTIONS: Options = ...
class Run(_ArgumentsManager, _ArgumentsProvider):
    """Base class providing common behaviour for pyreverse commands."""
    options = ...
    name = ...
    def __init__(self, args: Sequence[str]) -> NoReturn:
        ...

    def run(self, args: list[str]) -> int:
        """Checking arguments and run project."""
        ...



if __name__ == "__main__":
    ...
