"""
This type stub file was generated by pyright.
"""

import argparse
from collections.abc import Iterable
from pylint.pyreverse.diagrams import ClassDiagram, ClassEntity, DiagramEntity, PackageDiagram, PackageEntity
from pylint.pyreverse.printer import NodeProperties

"""Utilities for creating diagrams."""
class DiagramWriter:
    """Base class for writing project diagrams."""
    def __init__(self, config: argparse.Namespace) -> None:
        ...

    def write(self, diadefs: Iterable[ClassDiagram | PackageDiagram]) -> None:
        """Write files for <project> according to <diadefs>."""
        ...

    def write_packages(self, diagram: PackageDiagram) -> None:
        """Write a package diagram."""
        ...

    def write_classes(self, diagram: ClassDiagram) -> None:
        """Write a class diagram."""
        ...

    def set_printer(self, file_name: str, basename: str) -> None:
        """Set printer."""
        ...

    def get_package_properties(self, obj: PackageEntity) -> NodeProperties:
        """Get label and shape for packages."""
        ...

    def get_class_properties(self, obj: ClassEntity) -> NodeProperties:
        """Get label and shape for classes."""
        ...

    def get_shape_color(self, obj: DiagramEntity) -> str:
        """Get shape color."""
        ...

    def save(self) -> None:
        """Write to disk."""
        ...
