"""
This type stub file was generated by pyright.
"""

from typing import Any

def bold(text: str) -> str:
    ...

def green(text: str, bold: bool = ...) -> str:
    ...

def yellow(text: str, bold: bool = ...) -> str:
    ...

def orange(text: str, bold: bool = ...) -> str:
    ...

def red(text: str, bold: bool = ...) -> str:
    ...

def muted(text: str) -> str:
    ...

def echo(*args: Any, **kwargs: Any) -> None:
    ...
