"""
This type stub file was generated by pyright.
"""

import curtsies.events
from typing import Sequence

"""Non-keyboard events used in bpython curtsies REPL"""
class ReloadEvent(curtsies.events.Event):
    """Request to rerun REPL session ASAP because imported modules changed"""
    def __init__(self, files_modified: Sequence[str] = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class RefreshRequestEvent(curtsies.events.Event):
    """Request to refresh REPL display ASAP"""
    def __repr__(self) -> str:
        ...
    


class ScheduledRefreshRequestEvent(curtsies.events.ScheduledEvent):
    """Request to refresh the REPL display at some point in the future

    Used to schedule the disappearance of status bar message that only shows
    for a few seconds"""
    def __init__(self, when: float) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class RunStartupFileEvent(curtsies.events.Event):
    """Request to run the startup file."""
    ...


class UndoEvent(curtsies.events.Event):
    """Request to undo."""
    def __init__(self, n: int = ...) -> None:
        ...
    


