"""
This type stub file was generated by pyright.
"""

from codeop import CommandCompiler

"""Tools for preparing code to be run in the REPL (removing blank lines,
etc)"""
indent_empty_lines_re = ...
tabs_to_spaces_re = ...
def indent_empty_lines(s: str, compiler: CommandCompiler) -> str:
    """Indents blank lines that would otherwise cause early compilation

    Only really works if starting on a new line"""
    ...

def leading_tabs_to_spaces(s: str) -> str:
    ...

def preprocess(s: str, compiler: CommandCompiler) -> str:
    ...

