"""
This type stub file was generated by pyright.
"""

def resetquit(builtins): # -> None:
    """Redefine builtins 'quit' and 'exit' not so close stdin"""
    ...

def monkeypatch_quit(): # -> None:
    ...

