"""
This type stub file was generated by pyright.
"""

from xml.etree.ElementTree import Element
from markdown import Extension, Markdown, treeprocessors

class ExternalLinksTreeProcessor(treeprocessors.Treeprocessor):
    """
    Adds target="_blank" and rel="noopener" to external links.
    """
    def run(self, root: Element) -> None:
        ...



class ExternalLinksExtension(Extension):
    def extendMarkdown(self, md: Markdown) -> None:
        ...
