"""
This type stub file was generated by pyright.
"""

from astroid import nodes
from astroid.manager import AstroidManager

"""Astroid hooks for the PyQT library."""
def transform_pyqt_signal(node: nodes.FunctionDef) -> None:
    ...

def transform_pyside_signal(node: nodes.FunctionDef) -> None:
    ...

def pyqt4_qtcore_transform(): # -> Module:
    ...

def register(manager: AstroidManager) -> None:
    ...
