"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

def pkg_resources_transform(): # -> Module:
    ...

def register(manager: AstroidManager) -> None:
    ...
