"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from astroid.context import InferenceContext
from astroid.manager import AstroidManager

if TYPE_CHECKING:
    ...
CLASS_GET_ITEM_TEMPLATE = ...
def easy_class_getitem_inference(node, context: InferenceContext | None = ...): # -> None:
    ...

def register(manager: AstroidManager) -> None:
    ...
