"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for numpy.random.mtrand module."""
def numpy_random_mtrand_transform(): # -> Module:
    ...

def register(manager: AstroidManager) -> None:
    ...
