"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for numpy ma module."""
def numpy_ma_transform(): # -> Module:
    """
    Infer the call of various numpy.ma functions.

    :param node: node to infer
    :param context: inference context
    """
    ...

def register(manager: AstroidManager) -> None:
    ...
