"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for numpy.core.numeric module."""
def numpy_core_numeric_transform(): # -> Module:
    ...

METHODS_TO_BE_INFERRED = ...
def register(manager: AstroidManager) -> None:
    ...
