"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for dateutil."""
def dateutil_transform(): # -> Module:
    ...

def register(manager: AstroidManager) -> None:
    ...
