"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid brain hints for some of the `http` module."""
def register(manager: AstroidManager) -> None:
    ...
