"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for the ssl library."""
def ssl_transform(): # -> Module:
    ...

def register(manager: AstroidManager) -> None:
    ...
