"""
This type stub file was generated by pyright.
"""

from astroid.context import InferenceContext
from astroid.nodes.node_classes import Attribute, Name

"""Different utilities for the numpy brains."""
NUMPY_VERSION_TYPE_HINTS_SUPPORT = ...
def numpy_supports_type_hints() -> bool:
    """Returns True if numpy supports type hints."""
    ...

def infer_numpy_member(src, node, context: InferenceContext | None = ...): # -> Generator[InferenceResult, None, None]:
    ...

def name_looks_like_numpy_member(member_name: str, node: Name) -> bool:
    """
    Returns True if the Name is a member of numpy whose
    name is member_name.
    """
    ...

def attribute_looks_like_numpy_member(member_name: str, node: Attribute) -> bool:
    """
    Returns True if the Attribute is a member of numpy whose
    name is member_name.
    """
    ...
