"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager

"""Astroid hooks for the Python 2 GObject introspection bindings.

Helps with understanding everything imported from 'gi.repository'
"""
_inspected_modules = ...
_identifier_re = ...
_special_methods = ...
def register(manager: AstroidManager) -> None:
    ...
