"""
This type stub file was generated by pyright.
"""

from astroid import BoundMethod
from astroid.interpreter import objectmodel
from astroid.manager import AstroidManager

"""Astroid hooks for understanding functools library module."""
LRU_CACHE = ...
class LruWrappedModel(objectmodel.FunctionModel):
    """Special attribute model for functions decorated with functools.lru_cache.

    The said decorators patches at decoration time some functions onto
    the decorated function.
    """
    @property
    def attr___wrapped__(self): # -> None:
        ...

    @property
    def attr_cache_info(self): # -> CacheInfoBoundMethod:
        class CacheInfoBoundMethod(BoundMethod):
            ...



    @property
    def attr_cache_clear(self): # -> BoundMethod:
        ...



_looks_like_partial = ...
def register(manager: AstroidManager) -> None:
    ...
