"""
This type stub file was generated by pyright.
"""

from astroid.manager import AstroidManager
from astroid.nodes.scoped_nodes import ClassDef

"""
Astroid hook for the attrs library

Without this hook pylint reports unsupported-assignment-operation
for attrs classes
"""
ATTRIB_NAMES = ...
NEW_ATTRS_NAMES = ...
ATTRS_NAMES = ...
def is_decorated_with_attrs(node, decorator_names=...) -> bool:
    """Return whether a decorated node has an attr decorator applied."""
    ...

def attr_attributes_transform(node: ClassDef) -> None:
    """Given that the ClassNode has an attr decorator,
    rewrite class attributes as instance attributes
    """
    ...

def register(manager: AstroidManager) -> None:
    ...
