"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, TYPE_CHECKING
from marimo._config.config import DisplayConfig
from marimo._server.file_manager import AppFileManager
from marimo._server.models.export import ExportAsHTMLRequest
from marimo._server.session.session_view import SessionView

root = ...
if TYPE_CHECKING:
    ...
class Exporter:
    def export_as_html(self, *, file_manager: AppFileManager, session_view: SessionView, display_config: DisplayConfig, request: ExportAsHTMLRequest) -> tuple[str, str]:
        ...

    def export_as_script(self, file_manager: AppFileManager) -> tuple[str, str]:
        ...

    def export_as_ipynb(self, file_manager: AppFileManager, sort_mode: Literal["top-down", "topological"], session_view: Optional[SessionView] = ...) -> tuple[str, str]:
        """Export notebook as .ipynb, optionally including outputs if session_view provided."""
        ...

    def export_as_md(self, file_manager: AppFileManager) -> tuple[str, str]:
        ...



class AutoExporter:
    EXPORT_DIR = ...
    def save_html(self, file_manager: AppFileManager, html: str) -> None:
        ...

    def save_md(self, file_manager: AppFileManager, markdown: str) -> None:
        ...



def hash_code(code: str) -> str:
    ...
