"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple, Union

class _HTMLBuilder:
    @staticmethod
    def div(children: Union[str, List[str]], *, style: Optional[str] = ...) -> str:
        ...

    @staticmethod
    def img(*, src: Optional[str] = ..., alt: Optional[str] = ..., style: Optional[str] = ...) -> str:
        ...

    @staticmethod
    def video(*, src: Optional[str] = ..., controls: bool = ..., muted: bool = ..., autoplay: bool = ..., loop: bool = ..., style: Optional[str] = ...) -> str:
        ...

    @staticmethod
    def audio(*, src: Optional[str] = ..., controls: bool = ...) -> str:
        ...

    @staticmethod
    def iframe(*, src: Optional[str] = ..., srcdoc: Optional[str] = ..., width: Optional[str] = ..., height: Optional[str] = ..., style: Optional[str] = ..., onload: Optional[str] = ..., frameborder: Optional[str] = ..., **kwargs: str) -> str:
        ...

    @staticmethod
    def pre(child: str, style: Optional[str] = ...) -> str:
        ...

    @staticmethod
    def component(component_name: str, params: List[Tuple[str, Union[str, None]]]) -> str:
        ...

    @staticmethod
    def figure(children: Union[str, List[str]], *, style: Optional[str] = ...) -> str:
        ...

    @staticmethod
    def figcaption(children: Union[str, List[str]], *, style: Optional[str] = ...) -> str:
        ...



h = ...
