"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from marimo._output.hypertext import Html
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
@mddoc
def doc(obj: Any) -> Optional[Html]:
    """Get documentation about an object.

    If the object implements the `RichHelp` protocol, the documentation will be
    rendered as markdown.

    **Args.**

    - `obj`: The object to get documentation about.

    **Returns.**

    - Documentation as an `Html` object if the object implements `RichHelp`;
      otherwise, documentation is printed to console (and nothing is returned)
    """
    ...

