"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pylint.reporters.ureports.base_writer import BaseWriter
from pylint.reporters.ureports.nodes import EvaluationSection, Paragraph, Section, Table, Text, Title, VerbatimText

"""Text formatting drivers for ureports."""
if TYPE_CHECKING:
    ...
TITLE_UNDERLINES = ...
BULLETS = ...
class TextWriter(BaseWriter):
    """Format layouts as text
    (ReStructured inspiration but not totally handled yet).
    """
    def __init__(self) -> None:
        ...

    def visit_section(self, layout: Section) -> None:
        """Display a section as text."""
        ...

    def visit_evaluationsection(self, layout: EvaluationSection) -> None:
        """Display an evaluation section as a text."""
        ...

    def visit_title(self, layout: Title) -> None:
        ...

    def visit_paragraph(self, layout: Paragraph) -> None:
        """Enter a paragraph."""
        ...

    def visit_table(self, layout: Table) -> None:
        """Display a table as text."""
        ...

    def default_table(self, layout: Table, table_content: list[list[str]], cols_width: list[int]) -> None:
        """Format a table."""
        ...

    def visit_verbatimtext(self, layout: VerbatimText) -> None:
        """Display a verbatim layout as text (so difficult ;)."""
        ...

    def visit_text(self, layout: Text) -> None:
        """Add some text."""
        ...
