"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from marimo._runtime.app.common import RunOutput
from marimo._ast.app import InternalApp

if TYPE_CHECKING:
    ...
class AppScriptRunner:
    """Runs an app in a script context."""
    def __init__(self, app: InternalApp, filename: str | None) -> None:
        ...

    def run(self) -> RunOutput:
        ...
