"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional, Union
from marimo._config.config import PartialMarimoConfig

LOGGER = ...
def read_toml(file_path: Union[str, Path]) -> Dict[str, Any]:
    """Read and parse a TOML file."""
    ...

def read_marimo_config(path: str) -> PartialMarimoConfig:
    """Read the marimo.toml configuration."""
    ...

def read_pyproject_config(start_path: Union[str, Path]) -> Optional[PartialMarimoConfig]:
    """Read the pyproject.toml configuration."""
    ...

def find_nearest_pyproject_toml(start_path: Union[str, Path]) -> Optional[Path]:
    """Find the nearest pyproject.toml file."""
    ...
