"""
This type stub file was generated by pyright.
"""

from typing import TypeVar, Union
from marimo._config.config import MarimoConfig, PartialMarimoConfig

SECRET_PLACEHOLDER = ...
def mask_secrets(config: Union[MarimoConfig, PartialMarimoConfig]) -> MarimoConfig:
    ...

T = TypeVar("T")
def remove_secret_placeholders(config: T) -> T:
    ...
