"""
This type stub file was generated by pyright.
"""

class _Helper:
    def __init__(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __call__(self, *args, **kwargs) -> None:
        ...
    


_help = ...
