"""
This type stub file was generated by pyright.
"""

from typing import Match, Optional, Pattern
from functools import cached_property

class LazyReCompile:
    """Compile regular expressions on first use

    This class allows one to store regular expressions and compiles them on
    first use."""
    def __init__(self, regex: str, flags: int = ...) -> None:
        ...
    
    @cached_property
    def compiled(self) -> Pattern[str]:
        ...
    
    def finditer(self, *args, **kwargs): # -> Any:
        ...
    
    def search(self, *args, **kwargs) -> Optional[Match[str]]:
        ...
    
    def match(self, *args, **kwargs) -> Optional[Match[str]]:
        ...
    
    def sub(self, *args, **kwargs) -> str:
        ...
    


