"""
This type stub file was generated by pyright.
"""

from typing import Optional
from marimo._server.models.completion import AiCompletionContext, Language

language_rules = ...
class Prompter:
    def __init__(self, code: str) -> None:
        ...

    @staticmethod
    def get_system_prompt(*, language: Language, custom_rules: Optional[str] = ..., context: Optional[AiCompletionContext] = ...) -> str:
        ...

    def get_prompt(self, *, user_prompt: str, include_other_code: str) -> str:
        ...

    @staticmethod
    def get_chat_system_prompt(*, custom_rules: Optional[str] = ..., variables: Optional[list[str]] = ..., context: Optional[AiCompletionContext] = ..., include_other_code: str = ...) -> str:
        ...
