"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, TYPE_CHECKING
from marimo._ast.cell import Cell, CellId_t, CellImpl, SourcePosition
from marimo._ast.visitor import ImportData

if TYPE_CHECKING:
    ...
def code_key(code: str) -> int:
    ...

def cell_id_from_filename(filename: str) -> Optional[CellId_t]:
    """Parse cell id from filename."""
    ...

def get_filename(cell_id: CellId_t, suffix: str = ...) -> str:
    """Get a temporary Python filename that encodes the cell id in it."""
    ...

def cache(filename: str, code: str) -> None:
    ...

def fix_source_position(node: Any, source_position: SourcePosition) -> Any:
    ...

def compile_cell(code: str, cell_id: CellId_t, source_position: Optional[SourcePosition] = ..., carried_imports: list[ImportData] | None = ...) -> CellImpl:
    ...

def cell_factory(f: Callable[..., Any], cell_id: CellId_t, anonymous_file: bool = ...) -> Cell:
    """Creates a cell from a function.

    The signature and returns of the function are not used
    to generate refs and defs. If the user introduced errors to the
    signature, marimo will autofix them on save.
    """
    ...
