"""
This type stub file was generated by pyright.
"""

import ast

class NameTransformer(ast.NodeTransformer):
    def __init__(self, name_substitutions: dict[str, str]) -> None:
        ...

    def visit_Name(self, node: ast.Name) -> ast.Name:
        ...

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        ...

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        ...

    def visit_Assign(self, node: ast.Assign) -> ast.Assign:
        ...
