"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, Iterator, Optional, TYPE_CHECKING
from marimo._config.config import MarimoConfig
from marimo._runtime.context.types import ExecutionContext, RuntimeContext
from marimo._runtime.dataflow import DirectedGraph
from marimo._runtime.params import CLIArgs, QueryParams
from marimo._runtime.state import State
from marimo._ast.app import InternalApp
from marimo._ast.cell import CellId_t
from marimo._messaging.types import Stream

if TYPE_CHECKING:
    ...
@dataclass
class ScriptRuntimeContext(RuntimeContext):
    """Encapsulates runtime state when running as a script."""
    _app: InternalApp
    def __post_init__(self) -> None:
        ...

    @property
    def graph(self) -> DirectedGraph:
        ...

    @property
    def globals(self) -> dict[str, Any]:
        ...

    @property
    def execution_context(self) -> ExecutionContext | None:
        ...

    @property
    def marimo_config(self) -> MarimoConfig:
        ...

    @property
    def cell_id(self) -> Optional[CellId_t]:
        """Get the cell id of the currently executing cell, if any."""
        ...

    @property
    def cli_args(self) -> CLIArgs:
        """Get the CLI args."""
        ...

    @property
    def query_params(self) -> QueryParams:
        """Get the query params."""
        ...

    def get_ui_initial_value(self, object_id: str) -> Any:
        ...

    @contextmanager
    def provide_ui_ids(self, prefix: str) -> Iterator[None]:
        ...

    def take_id(self) -> str:
        ...

    def register_state_update(self, state: State[Any]) -> None:
        ...

    @contextmanager
    def with_cell_id(self, cell_id: CellId_t) -> Iterator[None]:
        ...

    @property
    def app(self) -> InternalApp:
        ...



def initialize_script_context(app: InternalApp, stream: Stream, filename: str | None) -> None:
    """Initializes thread-local/session-specific context.

    Must be called exactly once for each client thread.
    """
    ...
