"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from marimo._snippets.snippets import Snippets
from starlette.requests import Request

if TYPE_CHECKING:
    ...
LOGGER = ...
router = ...
_SNIPPETS: list[Snippets] = ...
@router.get("/snippets")
async def load_snippets(request: Request) -> Snippets:
    """
    responses:
        200:
            description: Load the snippets for the documentation page
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Snippets"
    """
    ...
