"""
This type stub file was generated by pyright.
"""

from starlette.websockets import WebSocket

LOGGER = ...
router = ...
@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    ...
