"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any

"""
This type stub file was generated by pyright.
"""
def set_config(**kwargs: Any) -> Callable[[Callable[..., None]], Callable[..., None]]:
    """Decorator for setting an option on the linter.

    Passing the args and kwargs back to the test function itself
    allows this decorator to be used on parameterized test cases.
    """
    ...

