"""
This type stub file was generated by pyright.
"""

from pylint.lint import PyLinter

"""
This type stub file was generated by pyright.
"""
def create_test_linter() -> PyLinter:
    ...

linter = ...
