"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, TYPE_CHECKING
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
def get_default_result_limit() -> Optional[int]:
    ...

@mddoc
def sql(query: str, output: bool = ...) -> Any:
    """
    Execute a SQL query.

    This uses duckdb to execute the query. Any dataframes in the global
    namespace can be used inside the query.

    The result of the query is displayed in the UI if output is True.

    Args:
        query: The SQL query to execute.
        output: Whether to display the result in the UI. Defaults to True.

    Returns:
        The result of the query.
    """
    ...

