"""
This type stub file was generated by pyright.
"""

from astroid.nodes.node_classes import AnnAssign, Arguments, Assert, Assign, AssignAttr, AssignName, AsyncFor, AsyncWith, Attribute, AugAssign, Await, BaseContainer, BinOp, BoolOp, Break, CONST_CLS, Call, Compare, Comprehension, Const, Continue, Decorators, DelAttr, DelName, Delete, Dict, DictUnpack, EmptyNode, EvaluatedObject, ExceptHandler, Expr, For, FormattedValue, Global, If, IfExp, Import, ImportFrom, JoinedStr, Keyword, List, Match, MatchAs, MatchCase, MatchClass, MatchMapping, MatchOr, MatchSequence, MatchSingleton, MatchStar, MatchValue, Name, NamedExpr, NodeNG, Nonlocal, ParamSpec, Pass, Pattern, Raise, Return, Set, Slice, Starred, Subscript, Try, TryStar, Tuple, TypeAlias, TypeVar, TypeVarTuple, UnaryOp, Unknown, While, With, Yield, YieldFrom, are_exclusive, const_factory, unpack_infer
from astroid.nodes.scoped_nodes import AsyncFunctionDef, ClassDef, ComprehensionScope, DictComp, FunctionDef, GeneratorExp, Lambda, ListComp, LocalsDictNodeNG, Module, SetComp, builtin_lookup, function_to_method, get_wrapping_class
from astroid.nodes.utils import Position

"""
This type stub file was generated by pyright.
"""
ALL_NODE_CLASSES = ...
__all__ = ("AnnAssign", "are_exclusive", "Arguments", "Assert", "Assign", "AssignAttr", "AssignName", "AsyncFor", "AsyncFunctionDef", "AsyncWith", "Attribute", "AugAssign", "Await", "BaseContainer", "BinOp", "BoolOp", "Break", "builtin_lookup", "Call", "ClassDef", "CONST_CLS", "Compare", "Comprehension", "ComprehensionScope", "Const", "const_factory", "Continue", "Decorators", "DelAttr", "Delete", "DelName", "Dict", "DictComp", "DictUnpack", "EmptyNode", "EvaluatedObject", "ExceptHandler", "Expr", "For", "FormattedValue", "FunctionDef", "function_to_method", "GeneratorExp", "get_wrapping_class", "Global", "If", "IfExp", "Import", "ImportFrom", "JoinedStr", "Keyword", "Lambda", "List", "ListComp", "LocalsDictNodeNG", "Match", "MatchAs", "MatchCase", "MatchClass", "MatchMapping", "MatchOr", "MatchSequence", "MatchSingleton", "MatchStar", "MatchValue", "Module", "Name", "NamedExpr", "NodeNG", "Nonlocal", "ParamSpec", "Pass", "Position", "Raise", "Return", "Set", "SetComp", "Slice", "Starred", "Subscript", "Try", "TryStar", "Tuple", "TypeAlias", "TypeVar", "TypeVarTuple", "UnaryOp", "Unknown", "unpack_infer", "While", "With", "Yield", "YieldFrom")
