"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def tree():
    """Return a tree of tuples representing the logger layout.

    Each tuple looks like ``('logger-name', <Logger>, [...])`` where the
    third element is a list of zero or more child tuples that share the
    same layout.

    """
    ...

