"""
This type stub file was generated by pyright.
"""

import click
import psutil
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    ...
@click.group(help="""Various commands for the marimo development.""", hidden=True)
def development() -> None:
    ...

@click.command(help="""Print the marimo OpenAPI schema""")
def openapi() -> None:
    """
    Example usage:

        marimo development openapi
    """
    ...

@click.group(help="Various commands for the marimo processes", hidden=True)
def ps() -> None:
    ...

def get_marimo_processes() -> list[psutil.Process]:
    ...

@ps.command(help="List the marimo processes", name="list")
def list_processes() -> None:
    """
    Example usage:

        marimo development ps list
    """
    ...

@ps.command(help="Kill the marimo processes")
def killall() -> None:
    """
    Example usage:

        marimo development ps killall
    """
    ...

@click.command(help="Inline packages according to PEP 723", name="inline-packages")
@click.argument("name", required=True)
def inline_packages(name: str) -> None:
    """
    Example usage:

        marimo development inline-packages

    This uses some heuristics to guess the package names from the imports in
    the file.

    Requires uv.
    Installation: https://docs.astral.sh/uv/getting-started/installation/
    """
    ...

@click.command(help="Print all routes")
def print_routes() -> None:
    ...
