"""
This type stub file was generated by pyright.
"""

import sys
from pathlib import Path
from typing import TYPE_CHECKING
from pylint.lint import PyLinter

"""Configuration file parser class."""
if sys.version_info >= (3, 11):
    ...
else:
    ...
if TYPE_CHECKING:
    ...
PylintConfigFileData = tuple[dict[str, str], list[str]]
class _RawConfParser:
    """Class to parse various formats of configuration files."""
    @staticmethod
    def parse_ini_file(file_path: Path) -> PylintConfigFileData:
        """Parse and handle errors of an ini configuration file.

        Raises ``configparser.Error``.
        """
        ...

    @staticmethod
    def parse_toml_file(file_path: Path) -> PylintConfigFileData:
        """Parse and handle errors of a toml configuration file.

        Raises ``tomllib.TOMLDecodeError``.
        """
        ...

    @staticmethod
    def parse_config_file(file_path: Path | None, verbose: bool) -> PylintConfigFileData:
        """Parse a config file and return str-str pairs.

        Raises ``tomllib.TOMLDecodeError``, ``configparser.Error``.
        """
        ...



class _ConfigurationFileParser:
    """Class to parse various formats of configuration files."""
    def __init__(self, verbose: bool, linter: PyLinter) -> None:
        ...

    def parse_config_file(self, file_path: Path | None) -> PylintConfigFileData:
        """Parse a config file and return str-str pairs."""
        ...
