"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class UnrecognizedArgumentAction(Exception):
    """Raised if an ArgumentManager instance tries to add an argument for which the
    action is not recognized.
    """
    ...


class _UnrecognizedOptionError(Exception):
    """Raised if an ArgumentManager instance tries to parse an option that is
    unknown.
    """
    def __init__(self, options: list[str], *args: object) -> None:
        ...



class ArgumentPreprocessingError(Exception):
    """Raised if an error occurs during argument pre-processing."""
    ...
