"""
This type stub file was generated by pyright.
"""

from typing import Any

def deep_merge(original: dict[Any, Any], update: dict[Any, Any]) -> dict[Any, Any]:
    """Deep merge of two dicts."""
    ...
