"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable

def deprecated(reason: str) -> Callable[[Any], Any]:
    """A decorator that emits a deprecation warning."""
    ...
