"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Union

class MarimoPath:
    """
    Wrapper around pathlib.Path to provide additional functionality for Marimo.
    And reduce API surface area of pathlib.Path.
    """
    def __init__(self, path: Union[str, Path], strict: bool = ...) -> None:
        ...

    def validate(self) -> None:
        ...

    @staticmethod
    def is_valid_path(path: Union[str, Path]) -> bool:
        ...

    def is_valid(self) -> bool:
        ...

    def is_python(self) -> bool:
        ...

    def is_markdown(self) -> bool:
        ...

    def rename(self, new_path: Path) -> None:
        ...

    def write_text(self, data: str, encoding: str = ...) -> None:
        ...

    def read_text(self, encoding: str = ...) -> str:
        ...

    @property
    def short_name(self) -> str:
        ...

    @property
    def relative_name(self) -> str:
        ...

    def is_relative_to(self, other: Path) -> bool:
        ...

    @property
    def absolute_name(self) -> str:
        ...

    @property
    def last_modified(self) -> float:
        ...

    def __str__(self) -> str:
        ...
