"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from pylint.utils import LinterStats

"""
This type stub file was generated by pyright.
"""
PYLINT_HOME_AS_PATH = ...
def load_results(base: str | Path, pylint_home: str | Path = ...) -> LinterStats | None:
    ...

def save_results(results: LinterStats, base: str | Path, pylint_home: str | Path = ...) -> None:
    ...
