"""
This type stub file was generated by pyright.
"""

from typing import Callable
from marimo._ast.cell import CellImpl
from marimo._runtime.runner import cell_runner

PreExecutionHookType = Callable[[CellImpl, cell_runner.Runner], None]
PRE_EXECUTION_HOOKS: list[PreExecutionHookType] = ...
