"""
This type stub file was generated by pyright.
"""

from typing import Callable
from marimo._runtime.runner import cell_runner

"""
This type stub file was generated by pyright.
"""
PreparationHookType = Callable[[cell_runner.Runner], None]
PREPARATION_HOOKS: list[PreparationHookType] = ...
