"""
This type stub file was generated by pyright.
"""

from typing import Callable
from marimo._runtime.runner import cell_runner

LOGGER = ...
OnFinishHookType = Callable[[cell_runner.Runner], None]
ON_FINISH_HOOKS: list[OnFinishHookType] = ...
