"""
This type stub file was generated by pyright.
"""

from marimo._output.formatters.formatter_factory import FormatterFactory

class CellFormatter(FormatterFactory):
    @staticmethod
    def package_name() -> None:
        ...

    def register(self) -> None:
        ...
