"""
This type stub file was generated by pyright.
"""

from typing import Any
from marimo._plugins.ui._impl.tables.table_manager import TableManager, TableManagerFactory

class IbisTableManagerFactory(TableManagerFactory):
    @staticmethod
    def package_name() -> str:
        ...

    @staticmethod
    def create() -> type[TableManager[Any]]:
        class IbisTableManager(TableManager[ibis.Table]):
            ...
