"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, List, Literal, Optional
from marimo._ai.types import ChatMessage

@dataclass
class SchemaColumn:
    name: str
    type: str
    sample_values: List[Any]
    ...


@dataclass
class SchemaTable:
    name: str
    columns: List[SchemaColumn]
    ...


@dataclass
class AiCompletionContext:
    schema: List[SchemaTable] = ...


Language = Literal["python", "markdown", "sql"]
@dataclass
class AiCompletionRequest:
    prompt: str
    include_other_code: str
    code: str
    context: Optional[AiCompletionContext] = ...
    language: Language = ...


@dataclass
class ChatRequest:
    context: AiCompletionContext
    include_other_code: str
    messages: List[ChatMessage]
    model: Optional[str] = ...
    variables: Optional[List[str]] = ...
