"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional

@dataclass
class ExportAsHTMLRequest:
    download: bool
    files: List[str]
    include_code: bool
    asset_url: Optional[str] = ...


@dataclass
class ExportAsScriptRequest:
    download: bool
    ...


@dataclass
class ExportAsMarkdownRequest:
    download: bool
    ...
