"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Literal, Optional
from marimo._server.models.models import BaseResponse

"""
This type stub file was generated by pyright.
"""
@dataclass
class FileInfo:
    id: str
    path: str
    name: str
    is_directory: bool
    is_marimo_file: bool
    last_modified: Optional[float] = ...
    children: List[FileInfo] = ...


@dataclass
class FileListRequest:
    path: Optional[str] = ...


@dataclass
class FileDetailsRequest:
    path: str
    ...


@dataclass
class FileOpenRequest:
    path: str
    ...


@dataclass
class FileTreeRequest:
    path: str
    ...


@dataclass
class FileCreateRequest:
    path: str
    type: Literal["file", "directory"]
    name: str
    contents: Optional[str] = ...


@dataclass
class FileDeleteRequest:
    path: str
    ...


@dataclass
class FileMoveRequest:
    path: str
    new_path: str
    ...


@dataclass
class FileUpdateRequest:
    path: str
    contents: str
    ...


@dataclass
class FileListResponse:
    files: List[FileInfo]
    root: str
    ...


@dataclass
class FileDetailsResponse:
    file: FileInfo
    contents: Optional[str] = ...
    mime_type: Optional[str] = ...


@dataclass
class FileCreateResponse(BaseResponse):
    message: Optional[str] = ...
    info: Optional[FileInfo] = ...


@dataclass
class FileDeleteResponse(BaseResponse):
    message: Optional[str] = ...


@dataclass
class FileUpdateResponse(BaseResponse):
    message: Optional[str] = ...
    info: Optional[FileInfo] = ...


@dataclass
class FileMoveResponse(BaseResponse):
    message: Optional[str] = ...
    info: Optional[FileInfo] = ...


