"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, TYPE_CHECKING
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.types import Lifespan

if TYPE_CHECKING:
    ...
LOGGER = ...
async def handle_error(request: Request, response: Any) -> Any:
    ...

def create_starlette_app(*, base_url: str, host: Optional[str] = ..., middleware: Optional[List[Middleware]] = ..., lifespan: Optional[Lifespan[Starlette]] = ..., enable_auth: bool = ..., allow_origins: Optional[tuple[str, ...]] = ..., lsp_port: Optional[int] = ...) -> Starlette:
    ...
