"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List
from marimo._server.models.home import MarimoFile

@dataclass
class RecentFilesState:
    files: List[str] = ...


_IGNORED_FOLDERS = ...
class RecentFilesManager:
    MAX_FILES = ...
    LOCATION = ...
    def __init__(self) -> None:
        ...

    def touch(self, filename: str) -> None:
        ...

    def rename(self, old_filename: str, new_filename: str) -> None:
        ...

    def get_recents(self) -> List[MarimoFile]:
        ...
