"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Callable, Optional, TYPE_CHECKING, TypeVar
from starlette.routing import Router

if TYPE_CHECKING:
    ...
LOGGER = ...
DecoratedCallable = TypeVar("DecoratedCallable", bound=Callable[..., Any])
@dataclass
class APIRouter(Router):
    def __init__(self, prefix: str = ...) -> None:
        ...

    def __post_init__(self) -> None:
        ...

    def post(self, path: str) -> Callable[[DecoratedCallable], DecoratedCallable]:
        """Post method that returns a JSON response"""
        ...

    def get(self, path: str, include_in_schema: bool = ..., name: Optional[str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]:
        """Get method."""
        ...

    def delete(self, path: str, include_in_schema: bool = ...) -> Callable[[DecoratedCallable], DecoratedCallable]:
        """Delete method."""
        ...

    def websocket(self, path: str) -> Callable[[DecoratedCallable], DecoratedCallable]:
        """Websocket method."""
        ...

    def include_router(self, router: APIRouter, prefix: str = ..., name: Optional[str] = ...) -> None:
        """Include another router in this one."""
        ...
