"""
This type stub file was generated by pyright.
"""

from typing import Optional
from marimo._runtime.requests import SerializedCLIArgs
from marimo._server.file_router import AppFileRouter
from marimo._server.model import SessionMode
from marimo._server.tokens import AuthToken

DEFAULT_PORT = ...
PROXY_REGEX = ...
def start(*, file_router: AppFileRouter, mode: SessionMode, development_mode: bool, quiet: bool, include_code: bool, headless: bool, port: Optional[int], host: str, proxy: Optional[str], watch: bool, cli_args: SerializedCLIArgs, base_url: str = ..., allow_origins: Optional[tuple[str, ...]] = ..., auth_token: Optional[AuthToken], redirect_console_to_browser: bool) -> None:
    """
    Start the server.
    """
    ...
