"""
This type stub file was generated by pyright.
"""

import multiprocessing as mp
from typing import TYPE_CHECKING, TypeVar, Union
from queue import Queue

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
T = TypeVar("T")
QueueType = Union["mp.Queue[T]", "Queue[T]"]
