"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple, TypeVar, Union
from marimo._ast.cell import CellId_t
from marimo._config.config import MarimoConfig
from marimo._data.models import DataTableSource

"""
This type stub file was generated by pyright.
"""
UIElementId = str
CompletionRequestId = str
FunctionCallId = str
T = TypeVar("T")
ListOrValue = Union[T, List[T]]
SerializedQueryParams = Dict[str, ListOrValue[str]]
Primitive = Union[str, bool, int, float]
SerializedCLIArgs = Dict[str, ListOrValue[Primitive]]
@dataclass
class ExecutionRequest:
    cell_id: CellId_t
    code: str
    timestamp: float = ...


@dataclass
class ExecuteStaleRequest:
    ...


@dataclass
class ExecuteMultipleRequest:
    cell_ids: List[CellId_t]
    codes: List[str]
    timestamp: float = ...
    @property
    def execution_requests(self) -> List[ExecutionRequest]:
        ...
    
    def __post_init__(self) -> None:
        ...
    


@dataclass
class ExecuteScratchpadRequest:
    code: str
    ...


@dataclass
class RenameRequest:
    filename: str
    ...


@dataclass
class SetUIElementValueRequest:
    object_ids: List[UIElementId]
    values: List[Any]
    token: str = ...
    def __post_init__(self) -> None:
        ...
    
    @staticmethod
    def from_ids_and_values(ids_and_values: List[Tuple[UIElementId, Any]]) -> SetUIElementValueRequest:
        ...
    
    @property
    def ids_and_values(self) -> List[Tuple[UIElementId, Any]]:
        ...
    


@dataclass
class FunctionCallRequest:
    function_call_id: FunctionCallId
    namespace: str
    function_name: str
    args: Dict[str, Any]
    ...


@dataclass
class AppMetadata:
    """Hold metadata about the app, like its filename."""
    query_params: SerializedQueryParams
    cli_args: SerializedCLIArgs
    filename: Optional[str] = ...


@dataclass
class SetCellConfigRequest:
    configs: Dict[CellId_t, Dict[str, Any]]
    ...


@dataclass
class SetUserConfigRequest:
    config: MarimoConfig
    ...


@dataclass
class CreationRequest:
    execution_requests: Tuple[ExecutionRequest, ...]
    set_ui_element_value_request: SetUIElementValueRequest
    ...


@dataclass
class DeleteCellRequest:
    cell_id: CellId_t
    ...


@dataclass
class StopRequest:
    ...


@dataclass
class CodeCompletionRequest:
    id: CompletionRequestId
    document: str
    cell_id: CellId_t
    ...


@dataclass
class InstallMissingPackagesRequest:
    manager: str
    versions: Dict[str, str]
    ...


@dataclass
class PreviewDatasetColumnRequest:
    source_type: DataTableSource
    source: str
    table_name: str
    column_name: str
    ...


ControlRequest = Union[ExecuteMultipleRequest, ExecuteScratchpadRequest, ExecuteStaleRequest, CreationRequest, DeleteCellRequest, FunctionCallRequest, RenameRequest, SetCellConfigRequest, SetUserConfigRequest, SetUIElementValueRequest, StopRequest, InstallMissingPackagesRequest, PreviewDatasetColumnRequest,]
