"""
This type stub file was generated by pyright.
"""

import weakref
from dataclasses import dataclass
from typing import Any, Callable, Generic, Optional, TypeVar
from marimo._output.rich_help import mddoc

"""
This type stub file was generated by pyright.
"""
T = TypeVar("T")
Id = int
@dataclass
class StateItem(Generic[T]):
    id: Id
    ref: weakref.ref[State[T]]
    ...


def extract_name(key: str) -> str:
    ...

class StateRegistry:
    def __init__(self) -> None:
        ...
    
    def register(self, state: State[T], name: Optional[str] = ..., context: Optional[str] = ...) -> None:
        ...
    
    def register_scope(self, glbls: dict[str, Any], defs: Optional[set[str]] = ...) -> None:
        """Finds instances of state and scope, and adds them to registry if not
        already present."""
        ...
    
    def retain_active_states(self, active_variables: set[str]) -> None:
        """Retains only the active states in the registry."""
        ...
    
    def lookup(self, name: str, context: Optional[str] = ...) -> Optional[State[T]]:
        ...
    
    def bound_names(self, state: State[T]) -> set[str]:
        ...
    


class State(Generic[T]):
    """Mutable reactive state"""
    def __init__(self, value: T, allow_self_loops: bool = ..., _registry: Optional[StateRegistry] = ..., _name: Optional[str] = ..., _context: Optional[str] = ...) -> None:
        ...
    
    def __call__(self) -> T:
        ...
    


class SetFunctor(Generic[T]):
    """Typed function tied to a state instance"""
    def __init__(self, state: State[T]) -> None:
        ...
    
    def __call__(self, update: T | Callable[[T], T]) -> None:
        ...
    


@mddoc
def state(value: T, allow_self_loops: bool = ...) -> tuple[State[T], Callable[[T], None]]:
    """Mutable reactive state

    This function takes an initial value and returns:

    - a getter function that reads the state value
    - a setter function to set the state's value

    When you call the setter function and update the state value in one cell,
    all *other* cells that read any global variables assigned to the getter
    will automatically run. By default, the cell that called the setter
    function won't be re-run, even if it references the getter; to allow a
    state setter to possibly run the caller cell, use the keyword argument
    `allow_self_loops=True`.

    You can use this function in conjunction with `UIElement` `on_change`
    handlers to trigger side-effects when an element's value is updated. For
    example, you can tie multiple UI elements to derive their values from
    shared state.

    **Basic Usage.**


    Create state:

    ```python
    get_count, set_count = mo.state(0)
    ```

    Read the value:

    ```python
    get_count()
    ```

    Update the state:

    ```
    set_count(1)
    ```

    Update the state based on the current value:

    ```
    set_count(lambda value: value + 1)
    ```

    *Note: Never mutate the state directly. You should only change its
    value through its setter.*

    **Synchronizing multiple UI elements.**

    ```python
    get_state, set_state = mo.state(0)
    ```

    ```python
    # updating the state through the slider will recreate the number (below)
    slider = mo.ui.slider(0, 100, value=get_state(), on_change=set_state)
    ```

    ```python
    # updating the state through the number will recreate the slider (above)
    number = mo.ui.number(0, 100, value=get_state(), on_change=set_state)
    ```

    ```python
    # slider and number are synchronized to have the same value (try it!)
    [slider, number]
    ```

    **Warning.** Do not store `marimo.ui` elements in state; doing so can
    lead to hard-to-diagnose bugs.

    **Args**:

    - `value`: initial value of the state
    - `allow_self_loops`: if True, if a cell calls a state setter
      and also references its getter, the caller cell will be re-run;
      defaults to `False`.



    **Returns**:

    - getter function that retrieves the state value
    - setter function that takes a new value, or a function taking the current
      value as its argument and returning a new value
    """
    ...

