"""
This type stub file was generated by pyright.
"""

import threading
from typing import TYPE_CHECKING
from multiprocessing import Queue

if TYPE_CHECKING:
    ...
class Win32InterruptHandler(threading.Thread):
    def __init__(self, interrupt_queue: Queue[bool]) -> None:
        ...

    def run(self) -> None:
        ...
