"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Optional

"""
This type stub file was generated by pyright.
"""
LOGGER = ...
@dataclass
class LayoutConfig:
    type: str
    data: dict[str, Any]
    ...


def save_layout_config(directory: str, app_name: str, config: LayoutConfig) -> str:
    """
    Save the layout configuration to disk
    at the given directory.

    The layout is saved as a JSON file under
        <directory>/layouts/<app_name>.{type}.json
    This allows:
        - all layouts to be saved in the same directory
        - multiple layouts to be saved for the same app
        - multiple apps can live in the same directory

    Returns: the path to the layout file
    """
    ...

def read_layout_config(directory: str, filename: str) -> Optional[LayoutConfig]:
    """
    Read the layout configuration from disk.

    Returns: the layout configuration
    """
    ...

