"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pylint.utils import register_plugins
from pylint.lint import PyLinter

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
def initialize(linter: PyLinter) -> None:
    """Initialize linter with checkers in the extensions' directory."""
    ...

__all__ = ["initialize"]
