"""
This type stub file was generated by pyright.
"""

from astroid.nodes.scoped_nodes.mixin import ComprehensionScope, LocalsDictNodeNG
from astroid.nodes.scoped_nodes.scoped_nodes import AsyncFunctionDef, ClassDef, DictComp, FunctionDef, GeneratorExp, Lambda, ListComp, Module, SetComp, _is_metaclass, function_to_method, get_wrapping_class
from astroid.nodes.scoped_nodes.utils import builtin_lookup

"""
This type stub file was generated by pyright.
"""
__all__ = ("AsyncFunctionDef", "ClassDef", "ComprehensionScope", "DictComp", "FunctionDef", "GeneratorExp", "Lambda", "ListComp", "LocalsDictNodeNG", "Module", "SetComp", "builtin_lookup", "function_to_method", "get_wrapping_class", "_is_metaclass")
