"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from astroid import nodes

"""This module contains utility functions for scoped nodes."""
if TYPE_CHECKING:
    ...
def builtin_lookup(name: str) -> tuple[nodes.Module, list[nodes.NodeNG]]:
    """Lookup a name in the builtin module.

    Return the list of matching statements and the ast for the builtin module
    """
    ...
