"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from typing import NamedTuple

OPTION_RGX = ...
OPTION_PO = ...
class PragmaRepresenter(NamedTuple):
    action: str
    messages: list[str]
    ...


ATOMIC_KEYWORDS = ...
MESSAGE_KEYWORDS = ...
ALL_KEYWORDS = ...
TOKEN_SPECIFICATION = ...
TOK_REGEX = ...
def emit_pragma_representer(action: str, messages: list[str]) -> PragmaRepresenter:
    ...

class PragmaParserError(Exception):
    """A class for exceptions thrown by pragma_parser module."""
    def __init__(self, message: str, token: str) -> None:
        """:args message: explain the reason why the exception has been thrown
        :args token: token concerned by the exception.
        """
        ...



class UnRecognizedOptionError(PragmaParserError):
    """Thrown in case the of a valid but unrecognized option."""
    ...


class InvalidPragmaError(PragmaParserError):
    """Thrown in case the pragma is invalid."""
    ...


def parse_pragma(pylint_pragma: str) -> Generator[PragmaRepresenter]:
    ...
