"""
This type stub file was generated by pyright.
"""

from pylint.config._pylint_config.main import _handle_pylint_config_commands
from pylint.config._pylint_config.setup import _register_generate_config_options

"""Everything related to the 'pylint-config' command.

Everything in this module is private.
"""
__all__ = ("_handle_pylint_config_commands", "_register_generate_config_options")
