"""
This type stub file was generated by pyright.
"""

import argparse
from collections.abc import Sequence
from typing import Any
from pylint.config.callback_actions import _AccessParserAction

"""Everything related to the setup of the 'pylint-config' command."""
class _HelpAction(_AccessParserAction):
    def __call__(self, parser: argparse.ArgumentParser, namespace: argparse.Namespace, values: str | Sequence[Any] | None, option_string: str | None = ...) -> None:
        ...
