"""
This type stub file was generated by pyright.
"""

import collections
from .tracer import Tracer as snoop
from .variables import Attrs, Exploding, Indices, Keys

"""
This type stub file was generated by pyright.
"""
__VersionInfo = ...
__version__ = ...
__version_info__ = ...
