"""
This type stub file was generated by pyright.
"""

import astroid
from collections.abc import Container, Iterable
from astroid import nodes
from pylint.checkers import utils
from pylint.checkers.base_checker import BaseChecker
from pylint.typing import MessageDefinitionTuple

"""
This type stub file was generated by pyright.
"""
ACCEPTABLE_NODES = ...
class DeprecatedMixin(BaseChecker):
    """A mixin implementing logic for checking deprecated symbols.

    A class implementing mixin must define "deprecated-method" Message.
    """
    DEPRECATED_ATTRIBUTE_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    DEPRECATED_MODULE_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    DEPRECATED_METHOD_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    DEPRECATED_ARGUMENT_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    DEPRECATED_CLASS_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    DEPRECATED_DECORATOR_MESSAGE: dict[str, MessageDefinitionTuple] = ...
    @utils.only_required_for_messages("deprecated-attribute")
    def visit_attribute(self, node: astroid.Attribute) -> None:
        """Called when an `astroid.Attribute` node is visited."""
        ...

    @utils.only_required_for_messages("deprecated-method", "deprecated-argument", "deprecated-class")
    def visit_call(self, node: nodes.Call) -> None:
        """Called when a :class:`nodes.Call` node is visited."""
        ...

    @utils.only_required_for_messages("deprecated-module", "deprecated-class")
    def visit_import(self, node: nodes.Import) -> None:
        """Triggered when an import statement is seen."""
        ...

    def deprecated_decorators(self) -> Iterable[str]:
        """Callback returning the deprecated decorators.

        Returns:
            collections.abc.Container of deprecated decorator names.
        """
        ...

    @utils.only_required_for_messages("deprecated-decorator")
    def visit_decorators(self, node: nodes.Decorators) -> None:
        """Triggered when a decorator statement is seen."""
        ...

    @utils.only_required_for_messages("deprecated-module", "deprecated-class")
    def visit_importfrom(self, node: nodes.ImportFrom) -> None:
        """Triggered when a from statement is seen."""
        ...

    def deprecated_methods(self) -> Container[str]:
        """Callback returning the deprecated methods/functions.

        Returns:
            collections.abc.Container of deprecated function/method names.
        """
        ...

    def deprecated_arguments(self, method: str) -> Iterable[tuple[int | None, str]]:
        """Callback returning the deprecated arguments of method/function.

        Args:
            method (str): name of function/method checked for deprecated arguments

        Returns:
            collections.abc.Iterable in form:
                ((POSITION1, PARAM1), (POSITION2: PARAM2) ...)
            where
                * POSITIONX - position of deprecated argument PARAMX in function definition.
                  If argument is keyword-only, POSITIONX should be None.
                * PARAMX - name of the deprecated argument.
            E.g. suppose function:

            .. code-block:: python
                def bar(arg1, arg2, arg3, arg4, arg5='spam')

            with deprecated arguments `arg2` and `arg4`. `deprecated_arguments` should return:

            .. code-block:: python
                ((1, 'arg2'), (3, 'arg4'))
        """
        ...

    def deprecated_modules(self) -> Iterable[str]:
        """Callback returning the deprecated modules.

        Returns:
            collections.abc.Container of deprecated module names.
        """
        ...

    def deprecated_classes(self, module: str) -> Iterable[str]:
        """Callback returning the deprecated classes of module.

        Args:
            module (str): name of module checked for deprecated classes

        Returns:
            collections.abc.Container of deprecated class names.
        """
        ...

    def deprecated_attributes(self) -> Iterable[str]:
        """Callback returning the deprecated attributes."""
        ...

    def check_deprecated_attribute(self, node: astroid.Attribute) -> None:
        """Checks if the attribute is deprecated."""
        ...

    def check_deprecated_module(self, node: nodes.Import, mod_path: str | None) -> None:
        """Checks if the module is deprecated."""
        ...

    def check_deprecated_method(self, node: nodes.Call, inferred: nodes.NodeNG) -> None:
        """Executes the checker for the given node.

        This method should be called from the checker implementing this mixin.
        """
        ...

    def check_deprecated_class(self, node: nodes.NodeNG, mod_name: str, class_names: Iterable[str]) -> None:
        """Checks if the class is deprecated."""
        ...

    def check_deprecated_class_in_call(self, node: nodes.Call) -> None:
        """Checks if call the deprecated class."""
        ...
