"""
This type stub file was generated by pyright.
"""

import io
from typing import Optional, Union

def guess_mime_type(src: Union[str, bytes, io.BytesIO, io.BufferedReader, None]) -> Optional[str]:
    """Guess the MIME type of a file."""
    ...

def mime_type_to_ext(mime_type: str) -> Optional[str]:
    ...

def io_to_data_url(src: Union[str, bytes, io.BytesIO, None], fallback_mime_type: str) -> Optional[str]:
    """Convert a file-like object to a data URL."""
    ...

def is_data_empty(data: Union[str, bytes, io.BytesIO]) -> bool:
    """Check if a data object is empty."""
    ...
