"""
This type stub file was generated by pyright.
"""

import os

"""
This type stub file was generated by pyright.
"""
STREAM = ...
SHOULD_ENCODE = ...
SUPPORTS_COLOR = ...
def get_terminfo_file():
    ...

class ProxyBufferStreamWrapper:
    def __init__(self, wrapped) -> None:
        ...
    
    def __getattr__(self, name):
        ...
    
    def write(self, text):
        ...
    


if os.name == 'nt':
    ...
else:
    ...
