"""
This type stub file was generated by pyright.
"""

from code import InteractiveConsole

"""
This type stub file was generated by pyright.
"""
REPL_ID_PREFIX = ...
repl = ...
class BetterExceptionsConsole(InteractiveConsole):
    def __init__(self) -> None:
        ...
    
    def runcode(self, code):
        ...
    
    def runsource(self, source, loc=..., symbol=...):
        ...
    
    def showtraceback(self):
        ...
    


def get_repl():
    ...

def interact(quiet=...):
    ...

