"""
This type stub file was generated by pyright.
"""

import narwhals.stable.v1 as nw
from typing import Any, Dict, Literal, TypedDict, Union
from narwhals.typing import IntoDataFrame

Data = Union[Dict[Any, Any], IntoDataFrame, nw.DataFrame[Any]]
_DataType = Union[Dict[Any, Any], IntoDataFrame, nw.DataFrame[Any]]
class _JsonFormatDict(TypedDict):
    type: Literal["json"]
    ...


class _CsvFormatDict(TypedDict):
    type: Literal["csv"]
    ...


class _ToJsonReturnUrlDict(TypedDict):
    url: str
    format: _JsonFormatDict
    ...


class _ToCsvReturnUrlDict(TypedDict):
    url: str
    format: _CsvFormatDict
    ...


def register_transformers() -> None:
    """
    Register custom data transformers for Altair.

    We register a CSV transformer and a JSON transformer. These
    transformers return a VirtualFile URL instead of writing to disk,
    which is the default behavior of Altair's to_csv and to_json.

    By registering these transformers, we are able to use
    much larger datasets.
    """
    ...
